name: Build

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    name: "Build bot"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "zulu"
      - run: ./gradlew check distTar
      - uses: actions/upload-artifact@v2
        with:
          name: "Kotlin Application"
          path: "build/distributions/tgto.tar"
          retention-days: 1
